dist: trusty
language: python
python:
  - 2.7
  - 3.5
addons:
  branches:
    - .*
  sonarqube:
    token:
      secure: "Thc5LaHc/10sDSP+kETD8IjtMRw4roiyjiMbfZlosebGp+O/KUF6EJ/6oy2bgoAEcJSRYQo6FqxzrY0s3gQJ/5N6gIMZzpVVpp8+YwvVcURbJ/uLPHGuR5zamPicYDZ2VG5evUixqhjsksagnLkasHfLJQG1if2Shd+skZAePOzuqxovt945S089bWDNl1BojESmd0Ejf+lTxU25FvWfGRxdx26EcfBYB5XOZ1kn7c0TotjuMcjUTslxecIK4dDPUfT/zT/Xx2n/zHmcBt0C+IFJ0I/LkEw+nTrzRoVx0E8zaStd9ae38AEauDjmqpTTBYcLexD0ytb4lG4g22y1hMDV/fNuU8fzb+q6UBLc9ZfxJKa4X0wjMfUk0kZP79tOiNwwJs4h/3XIaSII7E74jwQuTbL4F8uzv0fmAeCAUbEFEGsdR+7tBUtQpI/4j9rwa30ShW2V8RKZcPjY4Gg2PCkgUHP3cy9EUv1svhqRCMRLYwFlCxRTMNjw1L5461w8nl9JN+7RVNzfr1H43k8oqP7IMCNTNpm42IwGVZADYfUXNTY1pjw7on56D5zpvZ5yMUHopDqEa86FXtko+NvseiogbMbCCYGM4Fs/NBqd0FnHsbcPyPhy1CbDqi6CWSulXnIkUccV4NNFE6eodk/wiusnoRO6dXkIFEDYMUNmm5c="
install:
  - pip install tox
  - pip install codeclimate-test-reporter
env:
  - secure: "KK2H138WNxaWZitF0Nu2Ndb/xWAEeYJcsKEokXPUBujy8v1/jNDzDIfnP0W1AcipQeY6PkITCqmS0I5JHb2dZu3gRG91CAkU5hC8D1Td6HEBWp35ihQjG9EyH3m2whlLXD30Nim8fFMMaeVZxSy2RFf5iTRybjdtoTLKaPXGGvK1OPsplyKEOw8uN1vWF/AH+ZImbprVLvTNLKghucpOTa5nY5GNiHGWBVoL5JPn+cluI2f8wwmT9paN02Hw05t7JNyCmTetMkIAWhcHKH/QiR2LeHUdKhxgrhy1Q8q6dYMDYer/ucqVXCEQPDh+IFpgMobz+KmYU4wNavurSDuGBfThhn2qdI1iZlNwnMKxXWMDxnzLBd+EchAO/OV6prDtxpX6xi+8X+6iGl7VwekcMhf0synq6CTIWlg9aqLJEtsEpqs/lZNs9ZYORx2T9SQYc1zPgrt50jKkh1eVfGZN5TscSa20aHb7xVusJJjcpIm9aO2yaqmpn9O3yfBBnm2Rdj8hSpu6+j1EOzXhExOnluPlXY1jglJ7h5J6vRkJXtEjRPEN0IYVRcjr+drD43ML8zd2uwkvjjt0MpplTy9jYJRj5VT6m/zujtxv+0fyMXAs7561pID+pjffrHmxBiEuouLAQRtl662QM9DfYnEvMdPYs8OnxHBDjzVWmC1pDU4="
script:
  - sonar-scanner
  - tox -e py$(echo $TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - codeclimate-test-reporter
